"""Streamlit application for exploring Bank Marketing model predictions."""

from pathlib import Path
import pickle

import joblib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import streamlit as st
from sklearn.metrics import (
	accuracy_score,
	confusion_matrix,
	f1_score,
	matthews_corrcoef,
	precision_score,
	recall_score,
	roc_auc_score,
)


PROJECT_ROOT = Path(__file__).resolve().parent
MODEL_DIR = PROJECT_ROOT / "model"
TARGET_COLUMN = "y"
MODEL_FILES = {
	"Logistic Regression": "logistic_regression.pkl",
	"Decision Tree": "decision_tree.pkl",
	"K-Nearest Neighbor": "knn.pkl",
	"Naive Bayes": "naive_bayes.pkl",
	"Random Forest": "random_forest.pkl",
}
METRIC_COLUMNS = ["Accuracy", "AUC", "Precision", "Recall", "F1", "MCC"]


st.set_page_config(
	page_title="Model Prediction Explorer",
	page_icon="📊",
	layout="wide",
)

st.markdown(
	"""
	<style>
	.main { background: #f7f4ee; }
	.block-container { padding-top: 2.5rem; max-width: 1200px; }
	h1, h2, h3 { color: #173f5f; }
	.app-header { color: #173f5f; font-size: 2.35rem; font-weight: 800;
				 text-align: center; margin: 0 0 1.5rem; }
	.eyebrow { color: #ed553b; font-size: .78rem; font-weight: 700;
			   letter-spacing: .12em; text-align: center; text-transform: uppercase; }
	</style>
	""",
	unsafe_allow_html=True,
)


@st.cache_resource
def load_artifacts():
	"""Load the preprocessing artifacts and trained classifiers once."""
	with (MODEL_DIR / "encoders.pkl").open("rb") as file:
		encoders = pickle.load(file)
	with (MODEL_DIR / "scaler.pkl").open("rb") as file:
		scaler = pickle.load(file)
	models = {
		name: joblib.load(MODEL_DIR / filename)
		for name, filename in MODEL_FILES.items()
	}
	return encoders, scaler, models


@st.cache_data
def load_comparison_metrics():
	"""Load the metrics generated by the training workflow."""
	return pd.read_csv(MODEL_DIR / "comparison_metrics.csv").set_index("Model")


def prepare_features(dataframe, encoders, scaler):
	"""Encode uploaded categorical values and apply the saved scaler."""
	if TARGET_COLUMN not in dataframe.columns:
		raise ValueError("The CSV must include the target column 'y'.")

	feature_columns = list(scaler.feature_names_in_)
	missing_columns = [column for column in feature_columns if column not in dataframe]
	extra_columns = [
		column for column in dataframe.columns
		if column not in feature_columns and column != TARGET_COLUMN
	]
	if missing_columns or extra_columns:
		details = []
		if missing_columns:
			details.append(f"missing columns: {', '.join(missing_columns)}")
		if extra_columns:
			details.append(f"unexpected columns: {', '.join(extra_columns)}")
		raise ValueError("Invalid CSV schema (" + "; ".join(details) + ").")

	encoded = dataframe[feature_columns].copy()
	for column, encoder in encoders["features"].items():
		values = set(encoded[column].astype(str))
		unknown_values = sorted(values.difference(encoder.classes_))
		if unknown_values:
			raise ValueError(
				f"Column '{column}' contains unseen categories: "
				f"{', '.join(unknown_values[:5])}."
			)
		encoded[column] = encoder.transform(encoded[column].astype(str))
	return scaler.transform(encoded[feature_columns])


def calculate_metrics(target, predictions, probabilities):
	"""Calculate the six metrics required by the assignment."""
	return {
		"Accuracy": accuracy_score(target, predictions),
		"AUC": roc_auc_score(target, probabilities),
		"Precision": precision_score(target, predictions, zero_division=0),
		"Recall": recall_score(target, predictions, zero_division=0),
		"F1": f1_score(target, predictions, zero_division=0),
		"MCC": matthews_corrcoef(target, predictions),
	}


def render_confusion_matrix(target, predictions, target_encoder):
	"""Render a labelled confusion matrix for the selected model."""
	matrix = confusion_matrix(target, predictions, labels=[0, 1])
	labels = list(target_encoder.classes_)
	figure, axis = plt.subplots(figsize=(5, 4))
	sns.heatmap(
		matrix,
		annot=True,
		fmt="d",
		cmap="YlGnBu",
		cbar=False,
		xticklabels=labels,
		yticklabels=labels,
		ax=axis,
	)
	axis.set_xlabel("Predicted label")
	axis.set_ylabel("Actual label")
	axis.set_title("Confusion matrix")
	st.pyplot(figure, clear_figure=True)


def main():
	"""Render the interactive evaluation application."""
	st.markdown('<div class="app-header">Machine Learning - Assignment 2</div>', unsafe_allow_html=True)
	st.caption("Compare five classifiers and inspect predictions for a labelled test CSV.")

	try:
		encoders, scaler, models = load_artifacts()
		comparison_metrics = load_comparison_metrics()
	except (FileNotFoundError, pickle.UnpicklingError, ValueError) as error:
		st.error(f"Could not load the model artifacts: {error}")
		st.stop()
		return

	st.sidebar.header("Evaluation inputs")
	uploaded_file = st.sidebar.file_uploader(
		"Upload a test CSV",
		type="csv",
		help="Use test_data.csv, including the 16 predictors and the y target column.",
	)
	selected_model_name = st.sidebar.selectbox("Select a model", list(MODEL_FILES))

	if uploaded_file is None:
		st.info("Upload test_data.csv from the sidebar to begin model evaluation.")
		show_comparison = st.checkbox("Show all-model comparison")
		if show_comparison:
			st.subheader("All-model comparison")
			st.dataframe(comparison_metrics.style.format("{:.3f}"), width="stretch")
			st.bar_chart(comparison_metrics[METRIC_COLUMNS], y=METRIC_COLUMNS, height=360)
		return
		return

	try:
		uploaded_data = pd.read_csv(uploaded_file)
		scaled_features = prepare_features(uploaded_data, encoders, scaler)
		encoded_target = encoders["target"].transform(
			uploaded_data[TARGET_COLUMN].astype(str)
		)
	except (pd.errors.ParserError, UnicodeDecodeError, ValueError, KeyError) as error:
		st.error(f"The uploaded file could not be evaluated: {error}")
		st.stop()
		return

	st.success(f"Loaded {len(uploaded_data):,} rows from {uploaded_file.name}.")
	selected_model = models[selected_model_name]
	predictions = selected_model.predict(scaled_features)
	probabilities = selected_model.predict_proba(scaled_features)[:, 1]
	selected_metrics = calculate_metrics(encoded_target, predictions, probabilities)

	st.subheader(f"{selected_model_name} results")
	metrics_table = pd.DataFrame([selected_metrics], index=[selected_model_name])
	st.dataframe(metrics_table.style.format("{:.3f}"), width="stretch")

	st.subheader("Prediction details")
	matrix_column, chart_column = st.columns([1, 1])
	with matrix_column:
		render_confusion_matrix(encoded_target, predictions, encoders["target"])
	with chart_column:
		st.caption("Selected model metrics")
		st.bar_chart(pd.DataFrame([selected_metrics], index=[selected_model_name]), height=360)

	show_comparison = st.checkbox("Show all-model comparison")
	if show_comparison:
		st.subheader("All-model comparison")
		st.dataframe(comparison_metrics.style.format("{:.3f}"), width="stretch")
		st.bar_chart(comparison_metrics[METRIC_COLUMNS], y=METRIC_COLUMNS, height=360)

	show_uploaded_data = st.checkbox("Show uploaded sample data")
	if show_uploaded_data:
		st.subheader("Uploaded file (sample records)")
		st.dataframe(uploaded_data.head(10), width="stretch")


if __name__ == "__main__":
	main()